# Generated by Django 5.1.3 on 2024-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('obj_file', models.FileField(upload_to='models/obj_files/', verbose_name='File OBJ')),
                ('mtl_file', models.FileField(blank=True, null=True, upload_to='models/mtl_files/', verbose_name='File MTL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
            ],
        ),
    ]
