# Generated by Django 5.1.3 on 2025-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reperto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('immagine', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
