# Generated by Django 5.1.3 on 2025-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reperto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name_plural': 'Modelli'},
        ),
        migrations.AlterModelOptions(
            name='reperto',
            options={'verbose_name_plural': 'Reperti'},
        ),
        migrations.AlterField(
            model_name='reperto',
            name='categoria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='nome',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
