# Generated by Django 5.1.3 on 2025-08-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mymodel_options_alter_reperto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reperto',
            name='categoria',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='nome',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
