# Generated by Django 5.1.3 on 2025-08-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reperto_categoria_alter_reperto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='nome',
        ),
    ]
