# Generated by Django 5.1.3 on 2025-08-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_reperto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='reperto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelli', to='api.reperto', verbose_name='Reperto'),
        ),
    ]
