# Generated by Django 5.1.3 on 2025-08-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mymodel_reperto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reperto',
            options={'verbose_name_plural': 'Textures'},
        ),
        migrations.AddField(
            model_name='reperto',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrizione texture'),
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_file', models.ImageField(blank=True, null=True, upload_to='models/textures/', verbose_name='Texture')),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='api.mymodel', verbose_name='Modello')),
            ],
        ),
    ]
