# Generated by Django 5.1.3 on 2025-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reperto_options_reperto_description_texture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reperto',
            options={'verbose_name_plural': 'Reperti'},
        ),
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name_plural': 'Textures'},
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='description',
        ),
        migrations.AddField(
            model_name='texture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrizione texture'),
        ),
    ]
