# Generated by Django 5.1.3 on 2025-08-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reperto_options_alter_texture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='reperto',
        ),
        migrations.AddField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reperti', to='api.mymodel', verbose_name='Modello'),
        ),
    ]
