# Generated by Django 5.1.3 on 2025-09-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mymodel_reperto_reperto_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(verbose_name='Testo annotazione')),
                ('categoria', models.CharField(choices=[('misura', 'Misura'), ('materiale', 'Materiale'), ('danno', 'Danno'), ('restauro', 'Restauro'), ('descrizione', 'Descrizione')], default='descrizione', max_length=20)),
                ('posizione_x', models.FloatField(blank=True, null=True)),
                ('posizione_y', models.FloatField(blank=True, null=True)),
                ('posizione_z', models.FloatField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotazioni', to='api.mymodel')),
            ],
            options={
                'verbose_name_plural': 'Annotazioni',
            },
        ),
    ]
