# Generated by Django 5.1.3 on 2025-09-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_mymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reperti', to='api.mymodel', to_field='name', verbose_name='Modello'),
        ),
    ]
