# Generated by Django 5.1.3 on 2025-09-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mymodel_name_alter_reperto_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperti', to='api.mymodel', verbose_name='Modello'),
        ),
    ]
