# Generated by Django 5.1.3 on 2025-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reperto_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotazione',
            name='autore_cognome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome autore'),
        ),
        migrations.AddField(
            model_name='annotazione',
            name='autore_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome autore'),
        ),
    ]
