# Generated by Django 5.1.3 on 2025-09-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_annotazione_autore_cognome_annotazione_autore_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reperto',
            old_name='immagine',
            new_name='immagine_large',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='reperto',
            name='altezza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='categoria_materiale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='classe_produzione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='codice_inventario_patrimoniale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='comune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='data_inventario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='definizione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='denominazione_museo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='denominazione_raccolta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='diametro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='materia_tecnica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='nome_inventario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='regione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='riferimento_cronologico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='sezione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='specifiche_reperimento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='codice',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
