# Generated by Django 5.1.3 on 2025-09-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_immagine_reperto_immagine_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilazione',
            fields=[
                ('reperto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='compilazione', serialize=False, to='api.reperto')),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_compilatore', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondizioneGiuridica',
            fields=[
                ('reperto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='condizione_giuridica', serialize=False, to='api.reperto')),
                ('tipo_acquisizione', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('indicazione_generica', models.CharField(blank=True, max_length=255, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(blank=True, max_length=255, null=True)),
                ('autore', models.CharField(blank=True, max_length=255, null=True)),
                ('anno_edizione', models.CharField(blank=True, max_length=10, null=True)),
                ('sigla_citazione', models.CharField(blank=True, max_length=50, null=True)),
                ('citazione_completa', models.TextField(blank=True, null=True)),
                ('reperto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliografia', to='api.reperto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentazioneFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('ente_proprietario', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_identificativo', models.CharField(blank=True, max_length=50, null=True)),
                ('reperto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentazione_fotografica', to='api.reperto')),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_appartenenza', models.CharField(blank=True, max_length=255, null=True)),
                ('lingua', models.CharField(blank=True, max_length=50, null=True)),
                ('tecnica_scrittura', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_caratteri', models.CharField(blank=True, max_length=255, null=True)),
                ('posizione', models.CharField(blank=True, max_length=255, null=True)),
                ('trascrizione', models.TextField(blank=True, null=True)),
                ('reperto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='api.reperto')),
            ],
        ),
        migrations.CreateModel(
            name='Stemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_appartenenza', models.CharField(blank=True, max_length=255, null=True)),
                ('quantita', models.IntegerField(blank=True, null=True)),
                ('posizione', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('reperto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stemmi', to='api.reperto')),
            ],
        ),
    ]
