# Generated by Django 5.1.3 on 2025-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_compilazione_condizionegiuridica_bibliografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='altezza',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='diametro',
        ),
        migrations.AddField(
            model_name='reperto',
            name='misure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
