# Generated by Django 5.1.3 on 2025-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_reperto_altezza_remove_reperto_diametro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reperto',
            name='misure_varie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='notizie_storico_critiche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='specifiche_collocazione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='stato_conservazione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
