# Generated by Django 5.1.3 on 2025-10-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reperto_misure_varie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='immagine_large',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='ImmagineReperto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine_large', models.URLField(blank=True, null=True, verbose_name='Immagine Grande')),
                ('thumbnail', models.URLField(blank=True, null=True, verbose_name='Miniatura')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine di visualizzazione')),
                ('reperto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini_reperto', to='api.reperto')),
            ],
            options={
                'verbose_name_plural': 'Immagini Reperto',
                'ordering': ['reperto', 'ordine'],
            },
        ),
    ]
