# Generated by Django 5.1.3 on 2025-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_reperto_immagine_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='misure_varie',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='notizie_storico_critiche',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='specifiche_collocazione',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='stato_conservazione',
        ),
        migrations.AddField(
            model_name='reperto',
            name='immagine_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImmagineReperto',
        ),
    ]
