# Generated by Django 5.1.3 on 2025-10-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_reperto_misure_varie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='immagine_large',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='mymodel',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='reperto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelli_3d', to='api.reperto', verbose_name='Reperto Associato'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='misure_varie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Misure Varie'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='notizie_storico_critiche',
            field=models.TextField(blank=True, null=True, verbose_name='Notizie Storico-Critiche'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='provenienza_inventario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provenienza Inventario'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='specifiche_collocazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specifiche Collocazione'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='stato_conservazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stato Conservazione'),
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_large', models.URLField(blank=True, null=True, verbose_name='Immagine Grande (URL)')),
                ('url_thumbnail', models.URLField(blank=True, null=True, verbose_name='Thumbnail (URL)')),
                ('reperto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='api.reperto', verbose_name='Reperto')),
            ],
            options={
                'verbose_name_plural': 'Immagini Reperti',
                'ordering': ['id'],
            },
        ),
    ]
