# Generated by Django 5.1.3 on 2025-10-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_reperto_immagine_large_remove_reperto_mymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliografia',
            options={'verbose_name_plural': 'Bibliografia'},
        ),
        migrations.AlterModelOptions(
            name='compilazione',
            options={'verbose_name_plural': 'Compilazioni'},
        ),
        migrations.AlterModelOptions(
            name='condizionegiuridica',
            options={'verbose_name_plural': 'Condizioni Giuridiche'},
        ),
        migrations.AlterModelOptions(
            name='documentazionefotografica',
            options={'verbose_name_plural': 'Documentazione Fotografica'},
        ),
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name_plural': 'Modelli 3D'},
        ),
        migrations.AlterModelOptions(
            name='stemma',
            options={'verbose_name_plural': 'Stemmi'},
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='reperto',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='misure_varie',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='notizie_storico_critiche',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='provenienza_inventario',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='specifiche_collocazione',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='stato_conservazione',
        ),
        migrations.AddField(
            model_name='reperto',
            name='mymodel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperto_associato', to='api.mymodel', verbose_name='Modello 3D'),
        ),
    ]
