# Generated by Django 5.1.3 on 2025-10-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_bibliografia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliografia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compilazione',
            options={},
        ),
        migrations.AlterModelOptions(
            name='condizionegiuridica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentazionefotografica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iscrizione',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name_plural': 'Modelli'},
        ),
        migrations.AlterModelOptions(
            name='stemma',
            options={},
        ),
        migrations.AddField(
            model_name='reperto',
            name='immagine_large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reperto',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperti', to='api.mymodel', verbose_name='Modello'),
        ),
        migrations.DeleteModel(
            name='Immagine',
        ),
    ]
