# Generated by Django 5.1.3 on 2025-10-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_bibliografia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reperto',
            name='notizie_storico_critiche',
            field=models.TextField(blank=True, null=True, verbose_name='Notizie Storico-Critiche'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='provenienza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provenienza'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='stato_conservazione',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stato di Conservazione'),
        ),
    ]
