# Generated by Django 5.1.3 on 2025-10-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reperto_notizie_storico_critiche_reperto_provenienza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reperto',
            name='immagine_large',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='ImmagineReperto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_large', models.URLField(verbose_name='URL Immagine Grande')),
                ('url_thumbnail', models.URLField(blank=True, null=True, verbose_name='URL Miniatura')),
                ('reperto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='api.reperto', verbose_name='Reperto associato')),
            ],
            options={
                'verbose_name_plural': 'Immagini Reperti',
            },
        ),
    ]
