# Generated by Django 5.1.3 on 2025-10-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_reperto_immagine_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentazionefotografica',
            name='ente_proprietario',
        ),
        migrations.RemoveField(
            model_name='documentazionefotografica',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='documentazionefotografica',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='reperto',
            name='misure',
        ),
        migrations.AddField(
            model_name='documentazionefotografica',
            name='uso_foto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uso Foto (FTAS)'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='specifiche_collocazione',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Specifiche Collocazione'),
        ),
        migrations.AddField(
            model_name='reperto',
            name='tipologia_funzionale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipologia Funzionale'),
        ),
        migrations.AlterField(
            model_name='documentazionefotografica',
            name='codice_identificativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Identificativo (FTAN)'),
        ),
        migrations.CreateModel(
            name='Misura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo (MISZ)')),
                ('valore', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valore (MISM)')),
                ('unita', models.CharField(blank=True, max_length=15, null=True, verbose_name='Unità (MISU)')),
                ('varie', models.TextField(blank=True, null=True, verbose_name='Varie (MISV)')),
                ('reperto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misure_dettagliate', to='api.reperto', verbose_name='Reperto')),
            ],
            options={
                'verbose_name_plural': 'Misure',
            },
        ),
        migrations.CreateModel(
            name='ScavoArcheologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=250, null=True, verbose_name='Denominazione scavo (DSCV)')),
                ('riferimento_cronologico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rif. Cronologico (DSCD)')),
                ('responsabile_scientifico', models.CharField(blank=True, max_length=250, null=True, verbose_name='Responsabile (DSCA)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note (DSCN)')),
                ('reperto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scavi', to='api.reperto', verbose_name='Reperto')),
            ],
            options={
                'verbose_name_plural': 'Scavi Archeologici',
            },
        ),
    ]
