# Generated by Django 5.1.3 on 2025-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_documentazionefotografica_ente_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotazione',
            name='analisi_ia_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Analisi AI (NER)'),
        ),
    ]
