# Generated by Django 5.1.3 on 2025-11-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20251014_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcheoConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome Preferito (Italiano)')),
                ('source', models.CharField(default='AAT/ICCD', max_length=50, verbose_name='Sorgente (Thesaurus)')),
                ('keywords_text', models.TextField(verbose_name='Sinonimi e Keywords Associate (IT)')),
                ('embedding_vector', models.JSONField(help_text='Vettore numerico delle keywords.', verbose_name='Vettore Embedding (USE)')),
                ('expected_3d_type', models.CharField(choices=[('punto', 'Punto (Vertice o Punto di Riferimento)'), ('area', 'Area (Poligono o Selezione Areale)'), ('linea', 'Linea (Misura o Bordo)')], default='punto', max_length=10, verbose_name='Tipo di Geometria Attesa')),
            ],
            options={
                'verbose_name_plural': 'Concetti Archeologici (IA)',
            },
        ),
        migrations.AddField(
            model_name='annotazione',
            name='target_geometry_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Geometria Target (Poligono/Area)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='mtl_file',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='URL File MTL (GitHub Raw Link)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='obj_file',
            field=models.CharField(max_length=512, verbose_name='URL File OBJ (GitHub Raw Link)'),
        ),
        migrations.CreateModel(
            name='ModelPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_json', models.JSONField(verbose_name='Punti di Interesse 3D (Coords)')),
                ('source_algorithm', models.CharField(max_length=100, verbose_name='Algoritmo di Generazione')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archeoconcept', verbose_name='Concetto Correlato (Opzionale)')),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_pois', to='api.mymodel', verbose_name='Modello 3D')),
            ],
            options={
                'verbose_name_plural': 'Punti di Interesse Modelli (3D Snapping)',
                'unique_together': {('modello', 'source_algorithm')},
            },
        ),
    ]
