# Generated by Django 5.1.3 on 2026-01-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_archeoconcept_annotazione_target_geometry_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpoi',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archeoconcept', verbose_name='Concetto Correlato'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='mtl_file',
            field=models.FileField(blank=True, null=True, upload_to='models/mtl/', verbose_name='File MTL (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='obj_file',
            field=models.FileField(upload_to='models/obj/', verbose_name='File OBJ (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperti', to='api.mymodel', verbose_name='Modello 3D'),
        ),
    ]
