# Generated by Django 5.1.3 on 2026-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_modelpoi_concept_alter_mymodel_mtl_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='mtl_file',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL File MTL (Link Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='obj_file',
            field=models.URLField(max_length=512, verbose_name='URL File OBJ (Link Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='texture_file',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL Texture (Cloudinary)'),
        ),
    ]
