# Generated by Django 5.1.3 on 2026-01-23 13:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_mymodel_mtl_file_alter_mymodel_obj_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpoi',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archeoconcept', verbose_name='Concetto Correlato (Opzionale)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='mtl_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=api.models.path_modelli_3d, verbose_name='File MTL (Locale)'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='obj_file',
            field=models.FileField(max_length=512, upload_to=api.models.path_modelli_3d, verbose_name='File OBJ (Locale)'),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperti', to='api.mymodel', verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='texture_file',
            field=models.ImageField(blank=True, null=True, upload_to='models/textures/', verbose_name='Texture'),
        ),
    ]
