# Generated by Django 5.1.3 on 2026-01-24 21:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_modelpoi_concept_alter_mymodel_mtl_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpoi',
            options={'verbose_name_plural': 'Punti di Interesse 3D'},
        ),
        migrations.RemoveField(
            model_name='bibliografia',
            name='anno_edizione',
        ),
        migrations.RemoveField(
            model_name='bibliografia',
            name='autore',
        ),
        migrations.RemoveField(
            model_name='bibliografia',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='bibliografia',
            name='sigla_citazione',
        ),
        migrations.RemoveField(
            model_name='condizionegiuridica',
            name='indicazione_generica',
        ),
        migrations.RemoveField(
            model_name='condizionegiuridica',
            name='indirizzo',
        ),
        migrations.AlterField(
            model_name='annotazione',
            name='analisi_ia_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='annotazione',
            name='autore_cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotazione',
            name='autore_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotazione',
            name='target_geometry_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotazione',
            name='testo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archeoconcept',
            name='embedding_vector',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='archeoconcept',
            name='expected_3d_type',
            field=models.CharField(choices=[('punto', 'Punto'), ('area', 'Area'), ('linea', 'Linea')], default='punto', max_length=10),
        ),
        migrations.AlterField(
            model_name='archeoconcept',
            name='keywords_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archeoconcept',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='archeoconcept',
            name='source',
            field=models.CharField(default='AAT/ICCD', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentazionefotografica',
            name='codice_identificativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentazionefotografica',
            name='uso_foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='immaginereperto',
            name='reperto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='api.reperto'),
        ),
        migrations.AlterField(
            model_name='misura',
            name='reperto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misure_dettagliate', to='api.reperto'),
        ),
        migrations.AlterField(
            model_name='misura',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='unita',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='valore',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='misura',
            name='varie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelpoi',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archeoconcept'),
        ),
        migrations.AlterField(
            model_name='modelpoi',
            name='modello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_pois', to='api.mymodel'),
        ),
        migrations.AlterField(
            model_name='modelpoi',
            name='points_json',
            field=models.JSONField(verbose_name='Coordinate Punti Salienti'),
        ),
        migrations.AlterField(
            model_name='modelpoi',
            name='source_algorithm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reperto',
            name='mymodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reperti', to='api.mymodel', verbose_name='Modello 3D Associato'),
        ),
        migrations.AlterField(
            model_name='scavoarcheologico',
            name='denominazione',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scavoarcheologico',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scavoarcheologico',
            name='reperto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scavi', to='api.reperto'),
        ),
        migrations.AlterField(
            model_name='scavoarcheologico',
            name='responsabile_scientifico',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scavoarcheologico',
            name='riferimento_cronologico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='texture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='texture',
            name='modello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='api.mymodel'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='texture_file',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path_modelli_3d, verbose_name='File Immagine Texture'),
        ),
    ]
