# Generated by Django 5.1.3 on 2026-06-01 21:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_modelpoi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immaginereperto',
            name='didascalia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Didascalia / Tipo Vista'),
        ),
        migrations.AddField(
            model_name='immaginereperto',
            name='file_immagine',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=api.models.path_immagini_reperto, verbose_name='File Immagine Locale'),
        ),
        migrations.AlterField(
            model_name='immaginereperto',
            name='url_large',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL Immagine Esterna (Grande)'),
        ),
        migrations.AlterField(
            model_name='immaginereperto',
            name='url_thumbnail',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL Miniatura Esterna'),
        ),
    ]
